# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
            ],
        ),
    ]
