# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milyoncu', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
