# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milyoncu', '0006_auto_20171229_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
