# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milyoncu', '0007_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5555),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=5555),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=5555),
        ),
    ]
